namespace BH.SDK.Models.Enums.Meta
{
    // THREE STATES, NOT A BOOL, for the reason ResourceMeta.ResourceLicense defaults to
    // NoSpecifiedLicense: a bool's false would state "no AI" on the author's behalf for every record
    // nobody filled in, and a level that says "no" could not be told apart from one that said nothing.
    // NotSpecified is the zero value, so default, a fresh record, a migrated 1.0.0 file and a missing
    // key all mean "unknown" by construction.
    //
    // Both No and Yes are the author's own declaration, exactly like AgeRating - nothing verifies
    // either. Append-only: the value is what the file stores.

    /// <summary> Whether a piece of content was generated by AI, as declared by whoever authored the
    /// record. </summary>
    public enum AiGeneration : byte
    {
        /// <summary> The author has not said. Unknown - never read as "no". </summary>
        NotSpecified = 0,

        /// <summary> Declared as made without AI generation. </summary>
        No = 1,

        /// <summary> Declared as generated by AI. </summary>
        Yes = 2,
    }
}
