// ReSharper disable InconsistentNaming

namespace BH.SDK.Versions
{
    // THE GENERATIONS THEMSELVES, NAMED. A generation is a plain int, so without this every
    // [ModelGeneration] would carry a bare digit and the day a domain moves nobody could tell which
    // digits mean the same thing. A generation is assigned FORWARD, never reused, and taken from ONE
    // global counter: a domain that changes takes Current + 1, never "the next free number for that
    // domain". The twenty domains still diverge - only the one that changed moves, and only it needs
    // a snapshot and a migrator - but one number means one thing across all of them, which is what
    // keeps LevelMeta.MinGeneration against LevelGenerations.Required() an exact test.
    //
    // MIRRORED IN BH.SDK.Roslyn's ModelGenerationValues, which cannot reference this assembly at
    // all - the generator only sees the user's source through symbols. Invalid must agree there.

    /// <summary> Every model generation that exists, by name. </summary>
    public static class ModelGenerations
    {
        /// <summary> No generation at all - an unversioned leaf, or an envelope nothing was read
        /// from. NEGATIVE rather than zero, because zero is a real generation the frozen snapshots
        /// under <c>Versions/V0</c> are written at; every negative value is equally invalid and
        /// this is merely the canonical one. </summary>
        public const int Invalid = -1;

        /// <summary> The scaffold under <c>Versions/V0</c>: shapes that exercise the migration path
        /// end to end, rather than a format any build ever shipped. </summary>
        public const int Test = 0;

        /// <summary> What 1.0.0 shipped. Every live domain but <c>UserSettings</c>,
        /// <c>LevelStatistics</c>, <c>GameStatistics</c> and <c>LevelMeta</c> is still at it. </summary>
        public const int V1_AlphaRelease = 1;

        /// <summary> <c>UserSettings</c> remembers whether the tutorial was offered, and its controls
        /// move the cursor-return switch from the shared group onto each pointer device - what
        /// releasing a pointer does is that device's setting, on for the mouse and off for touch; a
        /// <c>LevelStatistics</c> record can be filed under "no collision", and <c>GameStatistics</c>
        /// counts completed tutorials - the first bump after release. <c>LevelMeta</c> joined it before
        /// any build carrying it shipped: a resource record can credit a theme, effect, shape or prefab
        /// (<c>ResourceMeta.ResourceGuid</c>), a record can describe the level's cover
        /// (<c>ResourceType.LevelLogo</c>), and the level and each record declare whether they were
        /// generated by AI (<c>AiGeneration</c>). <c>GraphicsSettings</c> gained the Colliders Only
        /// mode group (<c>CollidersModeGraphicsSettings</c>) before any release carrying the generation. </summary>
        public const int V2_SimplifyEntrance = 2;

        /// <summary> The newest generation there is - the only thing UI and reports read. A future
        /// bump adds its own named constant and moves this alias onto it. </summary>
        public const int Current = V2_SimplifyEntrance;
    }
}